#%RAML 1.0 DataType

properties:
  playerId:
    type: integer
    required: true
  playerName:
    type: integer
    required: true
  points:
    type: integer
    required: true
  storyPoints:
    type: integer
    required: true
  gold:
    type: integer
    required: true